baseURL = "https://em-yu.github.io"
languageCode = "en-us"
title = "Emilie Yu"
description = ""
# sectionPagesMenu = "main"
[params]
    [params.info]
        name = "Emilie Yu"
        description = "Post doctoral researcher at UCSB"
        twitter = "https://twitter.com/emxtyu"
        linkedin = "https://www.linkedin.com/in/emilie-yu-312003109/"
        github = "https://github.com/em-yu"
        cv = "media/CV_Emilie_Yu.pdf"
        email = "emxtyu@gmail.com"
    [params.style]
        primaryColor = "#2196F3"


[menu]
    # [[menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     title = "About"
    #     url = "/"
    #     weight = -120

    [[menu.main]]
        identifier = "research"
        name = "Research"
        title = "Research"
        url = "/#research"
        weight = -110

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        title = "Projects"
        url = "/#project"
        weight = -100

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        title = "Contact"
        url = "/#contact"
        weight = -90